### ISSUE TITLE
KVM VNC connection problem & etc

### ISSUE THREAD

**Issue by cr2025x1** [SmartX-Labs/Mini#3]
My VNC viewer can't connect to the VM.
From the host of VM, 'netstat -atun' indicates the port is open. One of its result includes:
tcp, 0, 0, 0.0.0.0:5905, 0.0.0.0:*, LISTEN

However, from my mac I cannot access into the VM even with proper IP and port. I'm currently using RealVNC Viewer from Mac. The viewer just closes off. But I still can confirm the viewer works as it did on previous other VM.

**Comment by smartx-hbyoon** [comment]
본 실험 환경은 Mac을 고려하지 않았습니다. 
정확한 원인 파악은 ubuntu에 질문하시는 것을 권장드립니다.

**Comment by cr2025x1** [comment]
Actually, it was found that this is my Mac specific problem. Even from Windows, this didn't work.
