### ISSUE TITLE
라즈베리 파이에 Net-SNMP를 설치하는 과정에 대한 질문이 있습니다.

### ISSUE THREAD

**Issue by jckwon** [SmartX-Labs/Mini#4]
![int](https://cloud.githubusercontent.com/assets/20151966/16411363/abd77922-3d61-11e6-9ab4-ff3643e9fe80.JPG)

현재 interconnect lab 실습을 진행 중인데요,
첨부한 슬라이드에 표시된 부분에 관련하여 질문이 있습니다.
이 내용으로는 어떤 부분을 수정해야 하는지 잘 이해가 되지 않는데,
조금 더 자세히 설명해 주시면 감사하겠습니다.

**Comment by smartx-cwkim** [comment]
When you type 'vi /etc/snmp/snmpd.conf', and you modify this.

![default](https://cloud.githubusercontent.com/assets/19545461/16414265/a0663370-3d71-11e6-986f-48fdbbed57aa.png)
