### ISSUE TITLE
Interconnect lap의 실습 결과가 예제와 다릅니다.

### ISSUE THREAD

**Issue by jckwon** [SmartX-Labs/Mini#5]
![interconnect_result](https://cloud.githubusercontent.com/assets/20151966/16437668/ca5a6184-3de3-11e6-89b3-401ce9f03f37.JPG)

interconnect lap의 실습 내용을 모두 수행하였는데,
최종 결과 화면이 슬라이드의 예제와 다릅니다.
정상적인 동작을 하고 있는게 맞는지 궁금합니다.

**Comment by smartx-srkim** [comment]
실습 자료가 새로이 갱신된 Flume source plugin의 내용을 반영하지 못해서 발생한 차이입니다.

이전 버전에서는 Timestamp를 1970년 1월 1일 UTC 이후로 경과한 시간을 밀리초 단위로 표현했으나,
KST로 변경하는 과정에서 포맷을 변경했습니다.
IP 주소 역시 루프백이나 도커 내부 인터페이스의 주소가 아니라 고유한 IP 주소를 가져올 수 있도록 변경했습니다.
그 외에 일부 OID의 추가, 변경이 있었으며, 해당 내용은 Flume agent 실행 이전의 설정 파일에서 확인할 수 있습니다.

첨부하신 내용은 정상적으로 출력된 결과로 보입니다.

**Comment by splguykr** [comment]
가능한 현재 버전의 프로그램과 보여지는 결과를 일치 시켜주기 바람.   또한 자주 변화가 예상되는 경우는 보여지는 결과는 프로그램
버전에 따라서 부분적으로 다를 수 있다고 "코멘트"를 추가해 주기 바람!

2016-06-30 16:30 GMT+09:00 Seungryong Kim <notifications@github.com>:

**Comment by smartx-cwkim** [comment]
해당 부분에 대해서는 자료를 수정하겠습니다. 감사합니다.

**Comment by smartx-cwkim** [comment]
해당 부분을 반영해서 InterConnect_Labs_v06.pdf 자료를 업데이트했습니다.

감사합니다.
