### ISSUE TITLE
Box 단계에서의 NUC 필요성

### ISSUE THREAD

**Issue by cr2025x1** [SmartX-Labs/Mini#7]
Box 단계에서의 세팅에 있어 NUC이 꼭 필요한지 궁금합니다. 일단 NUC을 가진 사람은 의외로 드물고, VM 상에서 세팅을 해도 될 것 같네요. 그리고 이럴 때는 Tower 단계 가이드처럼 KVM이 아니라 VMWare나 VBox를 써도 될 것 같고요.

**Comment by TaekhoNam** [comment]
해당 내용은 광주과학기술원 실습 수업을 위한 자료로 최초 제작되었습니다. 이런 이유로 인해, 실습실에 구비된 머신(NUC)에 한정하여 내용을 수록했는데 실제로는 자료에서 설명하는 OS(Ubuntu 14.04.3)이 동작하는 가용램이 2G 이상인 환경에서는 동작이 가능합니다.
