### ISSUE TITLE
WebApp Enide 2015 안내

### ISSUE THREAD

**Issue by cr2025x1** [SmartX-Labs/Mini#8]
PDF 상에 주어진 링크로 받은 파일에서는 아무런 실행 파일이 없어서 실행을 할 수가 없습니다. 웹서핑을 통해 따로 받은 Enide 2015에서야 실행이 가능했습니다.
그리고,

sudo nautilus ~/Downloads sudo nautilus /opt 라인과
sudo gedit /usr/share/applications/enide-2015-7.desktop 라인은

부분은 무엇을 의미하는지 잘 모르겠습니다.

**Comment by 2jungi** [comment]
링크 오류인것 같습니다. 수정을 진행하겠습니다.
또한 질문주신 커맨드 라인은 권한 설정에 관한 것으로 보입니다.
감사합니다.
