### ISSUE TITLE
Cluster Apache Mesos 세팅 문제

### ISSUE THREAD

**Issue by cr2025x1** [SmartX-Labs/Mini#9]
Apache Mesos를 설치할 때, 기존 Tower 단계를 따라 VM 상에 DevOpsTower를 세팅했는데 이 때 VM 세팅시 기본값인 NAT 설정으로 네트워크가 세팅되어서 NUC과 Tower간의 IP 서브넷이 달라져 서로 연결이 되지 않는 문제가 있습니다. 이 문제는 VM 세팅시 포트 포워딩으로 호스트의 포트와 게스트의 포트를 연결해줘도 여전히 발생했습니다.

**Comment by smartx-jwsong** [comment]
VM의 네트워크 설정을 Bridged로 변경하고 IP를 할당해주세요.
